import type {
  DocumentSpec,
  DocBlock,
  DocFormat,
  SheetDefinition,
  SlideDefinition,
  ThemeColors,
} from "./spec";
import { THEME_PALETTES, sanitizeFilename } from "./spec";

/**
 * Escapes a string to be safely embedded in Python code as a string literal.
 */
function pyStr(val: any): string {
  if (val === null || val === undefined) return '""';
  return JSON.stringify(String(val));
}

function hexToRgbTuple(hex: string): [number, number, number] {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.substring(0, 2), 16) / 255;
  const g = parseInt(clean.substring(2, 4), 16) / 255;
  const b = parseInt(clean.substring(4, 6), 16) / 255;
  return [r, g, b];
}

function resolveTargetFilename(spec: DocumentSpec, format: DocFormat): string {
  if (spec.filename && spec.filename.trim()) {
    return sanitizeFilename(format, spec.filename.trim());
  }
  if (spec.title && spec.title.trim()) {
    return sanitizeFilename(format, spec.title.trim());
  }
  return sanitizeFilename(format, "document");
}

function resolveEffectiveTitle(spec: DocumentSpec, targetFilename: string): string {
  const base = targetFilename.replace(/\.\w+$/, "").replace(/[_-]+/g, " ").trim();
  if (spec.title && spec.title.trim() && !/^(document|untitled|file)$/i.test(spec.title.trim())) {
    return spec.title.trim();
  }
  return base || "Document";
}

/**
 * Generates standalone Python code using ReportLab to create a PDF.
 */
export function generatePdfScript(spec: DocumentSpec): string {
  const theme: ThemeColors = (spec.theme && THEME_PALETTES[spec.theme]) || THEME_PALETTES.modern;
  const blocks = spec.blocks || [];
  const filename = resolveTargetFilename(spec, "pdf");
  const title = resolveEffectiveTitle(spec, filename);

  const scriptParts: string[] = [
    `"""`,
    `Generated by KSEMO Document Engine.`,
    `File: ${filename}`,
    `Title: ${title}`,
    `"""`,
    `import sys`,
    `import os`,
    `from reportlab.lib.pagesizes import letter`,
    `from reportlab.lib import colors`,
    `from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable`,
    `from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle`,
    `from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY`,
    `from reportlab.pdfgen import canvas`,
    ``,
    `class NumberedCanvas(canvas.Canvas):`,
    `    def __init__(self, *args, **kwargs):`,
    `        super().__init__(*args, **kwargs)`,
    `        self._saved_page_states = []`,
    ``,
    `    def showPage(self):`,
    `        self._saved_page_states.append(dict(self.__dict__))`,
    `        self._startPage()`,
    ``,
    `    def save(self):`,
    `        num_pages = len(self._saved_page_states)`,
    `        for state in self._saved_page_states:`,
    `            self.__dict__.update(state)`,
    `            self.draw_page_number(num_pages)`,
    `            super().showPage()`,
    `        super().save()`,
    ``,
    `    def draw_page_number(self, page_count):`,
    `        self.saveState()`,
    `        self.setFont("Helvetica", 9)`,
    `        self.setFillColor(colors.HexColor("#${theme.muted}"))`,
    `        page_text = f"Page {self._pageNumber} of {page_count}"`,
    `        self.drawRightString(letter[0] - 54, 36, page_text)`,
    `        self.restoreState()`,
    ``,
    `def build_pdf(filename=${pyStr(filename)}):`,
    `    doc = SimpleDocTemplate(`,
    `        filename,`,
    `        pagesize=letter,`,
    `        leftMargin=54,`,
    `        rightMargin=54,`,
    `        topMargin=54,`,
    `        bottomMargin=54`,
    `    )`,
    `    styles = getSampleStyleSheet()`,
    ``,
    `    title_style = ParagraphStyle(`,
    `        'DocTitle',`,
    `        parent=styles['Title'],`,
    `        fontName='Helvetica-Bold',`,
    `        fontSize=24,`,
    `        leading=28,`,
    `        textColor=colors.HexColor('#${theme.primary}'),`,
    `        alignment=TA_LEFT,`,
    `        spaceAfter=12`,
    `    )`,
    `    h1_style = ParagraphStyle(`,
    `        'Heading1_Custom',`,
    `        parent=styles['Heading1'],`,
    `        fontName='Helvetica-Bold',`,
    `        fontSize=18,`,
    `        leading=22,`,
    `        textColor=colors.HexColor('#${theme.primary}'),`,
    `        spaceBefore=14,`,
    `        spaceAfter=8`,
    `    )`,
    `    h2_style = ParagraphStyle(`,
    `        'Heading2_Custom',`,
    `        parent=styles['Heading2'],`,
    `        fontName='Helvetica-Bold',`,
    `        fontSize=14,`,
    `        leading=18,`,
    `        textColor=colors.HexColor('#${theme.secondary}'),`,
    `        spaceBefore=10,`,
    `        spaceAfter=6`,
    `    )`,
    `    body_style = ParagraphStyle(`,
    `        'Body_Custom',`,
    `        parent=styles['Normal'],`,
    `        fontName='Helvetica',`,
    `        fontSize=10,`,
    `        leading=14,`,
    `        textColor=colors.HexColor('#${theme.text}'),`,
    `        spaceAfter=8`,
    `    )`,
    `    bullet_style = ParagraphStyle(`,
    `        'Bullet_Custom',`,
    `        parent=body_style,`,
    `        leftIndent=15,`,
    `        firstLineIndent=-10,`,
    `        spaceAfter=4`,
    `    )`,
    `    callout_style = ParagraphStyle(`,
    `        'Callout_Custom',`,
    `        parent=body_style,`,
    `        fontName='Helvetica-Oblique',`,
    `        textColor=colors.HexColor('#${theme.primary}'),`,
    `        leftIndent=20,`,
    `        rightIndent=20`,
    `    )`,
    `    table_cell_style = ParagraphStyle(`,
    `        'TableCell',`,
    `        parent=styles['Normal'],`,
    `        fontName='Helvetica',`,
    `        fontSize=9,`,
    `        leading=12`,
    `    )`,
    `    table_head_style = ParagraphStyle(`,
    `        'TableHead',`,
    `        parent=table_cell_style,`,
    `        fontName='Helvetica-Bold',`,
    `        textColor=colors.white`,
    `    )`,
    ``,
    `    story = []`,
    `    story.append(Paragraph(${pyStr(title)}, title_style))`,
  ];

  if (spec.summary) {
    scriptParts.push(
      `    story.append(Paragraph(${pyStr(spec.summary)}, callout_style))`,
      `    story.append(Spacer(1, 10))`
    );
  }

  scriptParts.push(`    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#${theme.border}'), spaceAfter=14))`);

  for (const block of blocks) {
    if (block.type === "paragraph") {
      scriptParts.push(`    story.append(Paragraph(${pyStr(block.text)}, body_style))`);
    } else if (block.type === "heading") {
      const styleName = block.level === 1 ? "h1_style" : "h2_style";
      scriptParts.push(`    story.append(Paragraph(${pyStr(block.text)}, ${styleName}))`);
    } else if (block.type === "bulletList") {
      for (const item of block.items || []) {
        scriptParts.push(`    story.append(Paragraph('&bull; ' + ${pyStr(item)}, bullet_style))`);
      }
      scriptParts.push(`    story.append(Spacer(1, 6))`);
    } else if (block.type === "numberedList") {
      (block.items || []).forEach((item, idx) => {
        scriptParts.push(`    story.append(Paragraph('${idx + 1}. ' + ${pyStr(item)}, bullet_style))`);
      });
      scriptParts.push(`    story.append(Spacer(1, 6))`);
    } else if (block.type === "table") {
      const tableData = [];
      if (block.headers && block.headers.length > 0) {
        tableData.push(`[Paragraph(h, table_head_style) for h in ${JSON.stringify(block.headers)}]`);
      }
      for (const row of block.rows || []) {
        tableData.push(`[Paragraph(c, table_cell_style) for c in ${JSON.stringify(row)}]`);
      }
      scriptParts.push(`    t_data = [${tableData.join(', ')}]`);
      scriptParts.push(`    t = Table(t_data, colWidths=[(letter[0]-108)/max(1, len(t_data[0]))]*len(t_data[0]))`);
      scriptParts.push(`    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#${theme.primary}')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#${theme.border}')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#${theme.surface}')])
    ]))`);
      scriptParts.push(`    story.append(t)`);
      scriptParts.push(`    story.append(Spacer(1, 10))`);
    } else if (block.type === "callout") {
      scriptParts.push(`    story.append(Paragraph(${pyStr(block.text)}, callout_style))`);
      scriptParts.push(`    story.append(Spacer(1, 10))`);
    } else if (block.type === "quote") {
      scriptParts.push(`    story.append(Paragraph('&ldquo;' + ${pyStr(block.text)} + '&rdquo;', callout_style))`);
      if (block.author) {
        scriptParts.push(`    story.append(Paragraph('&mdash; ' + ${pyStr(block.author)}, body_style))`);
      }
      scriptParts.push(`    story.append(Spacer(1, 10))`);
    } else if (block.type === "pageBreak") {
      scriptParts.push(`    story.append(PageBreak())`);
    }
  }

  scriptParts.push(
    `    doc.build(story, canvasmaker=NumberedCanvas)`,
    ``,
    `if __name__ == '__main__':`,
    `    out_path = sys.argv[1] if len(sys.argv) > 1 else ${pyStr(filename)}`,
    `    build_pdf(out_path)`
  );

  return scriptParts.join("\n");
}

/**
 * Generates standalone Python code using python-docx to create a Word document.
 */
export function generateDocxScript(spec: DocumentSpec): string {
  const theme: ThemeColors = (spec.theme && THEME_PALETTES[spec.theme]) || THEME_PALETTES.modern;
  const blocks = spec.blocks || [];
  const filename = resolveTargetFilename(spec, "docx");
  const title = resolveEffectiveTitle(spec, filename);

  const scriptParts: string[] = [
    `"""`,
    `Generated by KSEMO Document Engine.`,
    `File: ${filename}`,
    `Title: ${title}`,
    `"""`,
    `import sys`,
    `from docx import Document`,
    `from docx.shared import Inches, Pt, RGBColor`,
    `from docx.enum.text import WD_ALIGN_PARAGRAPH`,
    `from docx.enum.table import WD_TABLE_ALIGNMENT`,
    `from docx.oxml import parse_xml`,
    `from docx.oxml.ns import nsdecls`,
    ``,
    `def build_docx(filename=${pyStr(filename)}):`,
    `    doc = Document()`,
    `    for section in doc.sections:`,
    `        section.top_margin = Inches(1)`,
    `        section.bottom_margin = Inches(1)`,
    `        section.left_margin = Inches(1)`,
    `        section.right_margin = Inches(1)`,
    ``,
    `    title_p = doc.add_heading(level=0)`,
    `    r = title_p.add_run(${pyStr(title)})`,
    `    r.font.name = 'Calibri'`,
    `    r.font.size = Pt(26)`,
    `    r.font.bold = True`,
    `    r.font.color.rgb = RGBColor.from_string('${theme.primary}')`,
    ``
  ];

  if (spec.summary) {
    scriptParts.push(
      `    p_sum = doc.add_paragraph()`,
      `    r_sum = p_sum.add_run(${pyStr(spec.summary)})`,
      `    r_sum.italic = True`,
      `    r_sum.font.color.rgb = RGBColor.from_string('${theme.muted}')`,
      `    doc.add_paragraph() # Spacing`
    );
  }

  for (const block of blocks) {
    if (block.type === "heading") {
      scriptParts.push(
        `    h = doc.add_heading(level=${Math.min(block.level, 3)})`,
        `    hr = h.add_run(${pyStr(block.text)})`,
        `    hr.font.color.rgb = RGBColor.from_string('${theme.primary}')`
      );
    } else if (block.type === "paragraph") {
      scriptParts.push(
        `    p = doc.add_paragraph()`,
        `    pr = p.add_run(${pyStr(block.text)})`,
        `    pr.font.size = Pt(11)`,
        `    pr.font.color.rgb = RGBColor.from_string('${theme.text}')`
      );
    } else if (block.type === "bulletList") {
      for (const item of block.items || []) {
        scriptParts.push(
          `    p = doc.add_paragraph(style='List Bullet')`,
          `    pr = p.add_run(${pyStr(item)})`,
          `    pr.font.size = Pt(11)`,
          `    pr.font.color.rgb = RGBColor.from_string('${theme.text}')`
        );
      }
    } else if (block.type === "numberedList") {
      for (const item of block.items || []) {
        scriptParts.push(
          `    p = doc.add_paragraph(style='List Number')`,
          `    pr = p.add_run(${pyStr(item)})`,
          `    pr.font.size = Pt(11)`,
          `    pr.font.color.rgb = RGBColor.from_string('${theme.text}')`
        );
      }
    } else if (block.type === "table") {
      const rows = block.rows || [];
      const hasHeaders = block.headers && block.headers.length > 0;
      const numRows = (hasHeaders ? 1 : 0) + rows.length;
      const numCols = hasHeaders ? block.headers!.length : (rows[0]?.length || 1);

      scriptParts.push(`    table = doc.add_table(rows=${numRows}, cols=${numCols})`);
      scriptParts.push(`    table.alignment = WD_TABLE_ALIGNMENT.CENTER`);
      scriptParts.push(`    table.style = 'Light Shading Accent 1' if 'Light Shading Accent 1' in [s.name for s in doc.styles] else 'Table Grid'`);

      let rIdx = 0;
      if (hasHeaders) {
        scriptParts.push(`    headers = ${JSON.stringify(block.headers)}`);
        scriptParts.push(`    for c_idx, h in enumerate(headers):`);
        scriptParts.push(`        cell = table.cell(${rIdx}, c_idx)`);
        scriptParts.push(`        cell.text = h`);
        scriptParts.push(`        for p in cell.paragraphs:`);
        scriptParts.push(`            for run in p.runs:`);
        scriptParts.push(`                run.font.bold = True`);
        rIdx++;
      }
      for (const row of rows) {
        scriptParts.push(`    row_data = ${JSON.stringify(row)}`);
        scriptParts.push(`    for c_idx, val in enumerate(row_data):`);
        scriptParts.push(`        table.cell(${rIdx}, c_idx).text = str(val)`);
        rIdx++;
      }
      scriptParts.push(`    doc.add_paragraph() # Spacing`);
    } else if (block.type === "callout" || block.type === "quote") {
      scriptParts.push(
        `    p = doc.add_paragraph()`,
        `    p.paragraph_format.left_indent = Inches(0.5)`,
        `    pr = p.add_run(${pyStr(block.text)})`,
        `    pr.italic = True`,
        `    pr.font.color.rgb = RGBColor.from_string('${theme.secondary}')`
      );
    } else if (block.type === "pageBreak") {
      scriptParts.push(`    doc.add_page_break()`);
    }
  }

  scriptParts.push(
    `    doc.save(filename)`,
    ``,
    `if __name__ == '__main__':`,
    `    out_path = sys.argv[1] if len(sys.argv) > 1 else ${pyStr(filename)}`,
    `    build_docx(out_path)`
  );

  return scriptParts.join("\n");
}

/**
 * Generates standalone Python code using openpyxl to create an Excel file.
 */
export function generateXlsxScript(spec: DocumentSpec): string {
  const sheets: SheetDefinition[] = spec.sheets && spec.sheets.length > 0 
    ? spec.sheets 
    : [{ name: "Sheet 1", rows: [["No Data"]] }];
  const filename = resolveTargetFilename(spec, "xlsx");
  const title = resolveEffectiveTitle(spec, filename);

  const scriptParts: string[] = [
    `"""`,
    `Generated by KSEMO Document Engine.`,
    `File: ${filename}`,
    `Workbook: ${title}`,
    `"""`,
    `import sys`,
    `from openpyxl import Workbook`,
    `from openpyxl.styles import Font, PatternFill, Alignment, Border, Side`,
    `from openpyxl.utils import get_column_letter`,
    ``,
    `def build_xlsx(filename=${pyStr(filename)}):`,
    `    wb = Workbook()`,
    `    # Remove default sheet to recreate clean sheets`,
    `    wb.remove(wb.active)`
  ];

  sheets.forEach((sheet, sIdx) => {
    const sheetVar = `ws_${sIdx}`;
    scriptParts.push(
      `    ${sheetVar} = wb.create_sheet(title=${pyStr(sheet.name || `Sheet${sIdx+1}`)})`,
      `    ${sheetVar}.views.sheetView[0].showGridLines = True`
    );

    const rows = sheet.rows || [];
    rows.forEach((row, rIdx) => {
      const rowIndex = rIdx + 1;
      row.forEach((cell, cIdx) => {
        const colIndex = cIdx + 1;
        if (typeof cell === "object" && cell !== null && "formula" in cell && cell.formula) {
          scriptParts.push(`    ${sheetVar}.cell(row=${rowIndex}, column=${colIndex}, value=${pyStr(cell.formula)})`);
        } else if (typeof cell === "object" && cell !== null && "value" in cell) {
          scriptParts.push(`    ${sheetVar}.cell(row=${rowIndex}, column=${colIndex}, value=${pyStr(cell.value)})`);
        } else {
          scriptParts.push(`    ${sheetVar}.cell(row=${rowIndex}, column=${colIndex}, value=${pyStr(cell)})`);
        }
      });
    });

    // Formatting: Header row styling if table=true or by default
    scriptParts.push(`    # Style header row`);
    scriptParts.push(`    header_font = Font(name='Calibri', size=11, bold=True, color='FFFFFF')`);
    scriptParts.push(`    header_fill = PatternFill(start_color='1F4E79', end_color='1F4E79', fill_type='solid')`);
    scriptParts.push(`    for cell in ${sheetVar}[1]:`);
    scriptParts.push(`        cell.font = header_font`);
    scriptParts.push(`        cell.fill = header_fill`);
    scriptParts.push(`        cell.alignment = Alignment(horizontal='center', vertical='center')`);

    // Auto-fit columns
    scriptParts.push(`    # Auto-adjust column widths`);
    scriptParts.push(`    for col in ${sheetVar}.columns:`);
    scriptParts.push(`        max_len = max(len(str(cell.value or '')) for cell in col)`);
    scriptParts.push(`        col_letter = get_column_letter(col[0].column)`);
    scriptParts.push(`        ${sheetVar}.column_dimensions[col_letter].width = max(max_len + 3, 12)`);
  });

  scriptParts.push(
    `    wb.save(filename)`,
    ``,
    `if __name__ == '__main__':`,
    `    out_path = sys.argv[1] if len(sys.argv) > 1 else ${pyStr(filename)}`,
    `    build_xlsx(out_path)`
  );

  return scriptParts.join("\n");
}

/**
 * Generates standalone Python code using python-pptx to create a PowerPoint deck.
 */
export function generatePptxScript(spec: DocumentSpec): string {
  const filename = resolveTargetFilename(spec, "pptx");
  const title = resolveEffectiveTitle(spec, filename);
  const slides: SlideDefinition[] = spec.slides && spec.slides.length > 0
    ? spec.slides
    : [{ title, subtitle: spec.summary || "" }];

  const scriptParts: string[] = [
    `"""`,
    `Generated by KSEMO Document Engine.`,
    `File: ${filename}`,
    `Presentation: ${title}`,
    `"""`,
    `import sys`,
    `from pptx import Presentation`,
    `from pptx.util import Inches, Pt`,
    `from pptx.dml.color import RGBColor`,
    `from pptx.enum.text import PP_ALIGN`,
    ``,
    `def build_pptx(filename=${pyStr(filename)}):`,
    `    prs = Presentation()`,
    `    prs.slide_width = Inches(13.333)`,
    `    prs.slide_height = Inches(7.5)`,
    `    blank_layout = prs.slide_layouts[6] # completely blank slide`,
    ``
  ];

  slides.forEach((slide, idx) => {
    scriptParts.push(`    # --- Slide ${idx + 1}: ${slide.title || "Slide"} ---`);
    scriptParts.push(`    slide = prs.slides.add_slide(blank_layout)`);
    
    // Background / banner
    scriptParts.push(`    # Title text box`);
    scriptParts.push(`    title_box = slide.shapes.add_textbox(Inches(0.8), Inches(0.8), Inches(11.7), Inches(1.2))`);
    scriptParts.push(`    tf = title_box.text_frame`);
    scriptParts.push(`    tf.word_wrap = True`);
    scriptParts.push(`    p = tf.paragraphs[0]`);
    scriptParts.push(`    p.text = ${pyStr(slide.title || '')}`);
    scriptParts.push(`    p.font.bold = True`);
    scriptParts.push(`    p.font.size = Pt(28)`);
    scriptParts.push(`    p.font.color.rgb = RGBColor(26, 54, 93)`);

    if (slide.subtitle) {
      scriptParts.push(`    sub_p = tf.add_paragraph()`);
      scriptParts.push(`    sub_p.text = ${pyStr(slide.subtitle)}`);
      scriptParts.push(`    sub_p.font.size = Pt(16)`);
      scriptParts.push(`    sub_p.font.color.rgb = RGBColor(100, 116, 139)`);
    }

    // Bullets or Content
    if (slide.bullets && slide.bullets.length > 0) {
      scriptParts.push(`    body_box = slide.shapes.add_textbox(Inches(0.8), Inches(2.2), Inches(11.7), Inches(4.5))`);
      scriptParts.push(`    btf = body_box.text_frame`);
      scriptParts.push(`    btf.word_wrap = True`);
      slide.bullets.forEach((bullet, bIdx) => {
        if (bIdx === 0) {
          scriptParts.push(`    bp = btf.paragraphs[0]`);
        } else {
          scriptParts.push(`    bp = btf.add_paragraph()`);
        }
        scriptParts.push(`    bp.text = "• " + ${pyStr(bullet)}`);
        scriptParts.push(`    bp.font.size = Pt(18)`);
        scriptParts.push(`    bp.font.color.rgb = RGBColor(51, 65, 85)`);
        scriptParts.push(`    bp.space_after = Pt(12)`);
      });
    }

    if (slide.columns && slide.columns.length > 0) {
      const colWidth = 11.5 / slide.columns.length;
      slide.columns.forEach((col, cIdx) => {
        const left = 0.8 + cIdx * colWidth;
        scriptParts.push(`    col_box_${cIdx} = slide.shapes.add_textbox(Inches(${left.toFixed(2)}), Inches(2.3), Inches(${(colWidth - 0.4).toFixed(2)}), Inches(4.2))`);
        scriptParts.push(`    ctf_${cIdx} = col_box_${cIdx}.text_frame`);
        scriptParts.push(`    ctf_${cIdx}.word_wrap = True`);
        if (col.title) {
          scriptParts.push(`    cp_${cIdx} = ctf_${cIdx}.paragraphs[0]`);
          scriptParts.push(`    cp_${cIdx}.text = ${pyStr(col.title)}`);
          scriptParts.push(`    cp_${cIdx}.font.bold = True`);
          scriptParts.push(`    cp_${cIdx}.font.size = Pt(18)`);
        }
        if (col.bullets) {
          col.bullets.forEach((b) => {
            scriptParts.push(`    cb = ctf_${cIdx}.add_paragraph()`);
            scriptParts.push(`    cb.text = "- " + ${pyStr(b)}`);
            scriptParts.push(`    cb.font.size = Pt(14)`);
          });
        }
      });
    }
  });

  scriptParts.push(
    `    prs.save(filename)`,
    ``,
    `if __name__ == '__main__':`,
    `    out_path = sys.argv[1] if len(sys.argv) > 1 else ${pyStr(filename)}`,
    `    build_pptx(out_path)`
  );

  return scriptParts.join("\n");
}

/**
 * Generates standalone Python code for plain text / markdown / CSV.
 */
export function generatePlainTextScript(spec: DocumentSpec): string {
  const format = (spec.format as DocFormat) || "txt";
  const filename = resolveTargetFilename(spec, format);
  const title = resolveEffectiveTitle(spec, filename);
  const contentStr = spec.blocks ? spec.blocks.map(b => {
    if (b.type === 'heading') return `${'#'.repeat(b.level)} ${b.text}\n`;
    if (b.type === 'paragraph') return `${b.text}\n`;
    if (b.type === 'bulletList') return (b.items || []).map(i => `* ${i}`).join('\n') + '\n';
    if (b.type === 'numberedList') return (b.items || []).map((item, i) => `${i + 1}. ${item}`).join('\n') + '\n';
    return '';
  }).join('\n') : title;

  return `"""
Generated by KSEMO Document Engine.
File: ${filename}
Title: ${title}
"""
import sys

def build_text(filename=${pyStr(filename)}):
    content = ${pyStr(contentStr)}
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(content)

if __name__ == '__main__':
    out_path = sys.argv[1] if len(sys.argv) > 1 else ${pyStr(filename)}
    build_text(out_path)
`;
}

/**
 * Main dispatcher to generate Python script given a DocumentSpec.
 */
export function generatePythonScript(spec: DocumentSpec): string {
  switch (spec.format as string) {
    case "pdf":
      return generatePdfScript(spec);
    case "docx":
      return generateDocxScript(spec);
    case "xlsx":
      return generateXlsxScript(spec);
    case "pptx":
      return generatePptxScript(spec);
    case "txt":
    case "markdown":
    case "csv":
    default:
      return generatePlainTextScript(spec);
  }
}
