export type FaqItem = { id: string; question: string; answer: string };
export type FaqCategory = { id: string; label: string; items: FaqItem[] };

export const FAQ_CATEGORIES: FaqCategory[] = [
  {
    id: "getting-started",
    label: "Getting started",
    items: [
      {
        id: "gs-1",
        question: "What is KSEMO?",
        answer:
          "KSEMO is your personal AI assistant for conversations and files. You can ask questions, analyze documents and images from your Library, use voice input, and — when you turn on Memory — let KSEMO remember facts about you so replies stay consistent and personal.",
      },
      {
        id: "gs-2",
        question: "How do I start my first conversation?",
        answer:
          "Sign in, then click “New chat” in the sidebar or press Ctrl/Cmd + Shift + O. Type your question in the message box at the bottom and press Enter or the send button.",
      },
      {
        id: "gs-3",
        question: "Is KSEMO free to use?",
        answer:
          "Access depends on how your KSEMO workspace is set up. If you can sign in and see the chat screen, your account already includes everything you see in the app.",
      },
      {
        id: "gs-4",
        question: "Which browsers work best with KSEMO?",
        answer:
          "KSEMO works on current versions of Chrome, Edge, Firefox, and Safari.",
      },
      {
        id: "gs-5",
        question: "Can I use KSEMO on my phone or tablet?",
        answer:
          "Yes. KSEMO adapts to smaller screens automatically. On mobile, open the sidebar with the menu button in the top-left corner of the chat area.",
      },
      {
        id: "gs-6",
        question: "How do I change how KSEMO responds?",
        answer:
          "Open Settings from your profile menu and go to Preferences. You can pick a response style — Balanced, Concise, Creative, or Analytical — and add custom instructions KSEMO will follow in every conversation.",
      },
      {
        id: "gs-7",
        question: "What can I ask KSEMO to do?",
        answer:
          "You can ask for explanations, writing help, planning, summaries of uploaded files, brainstorming, analysis, translations, and much more. If a request needs a file, attach it from your Library first.",
      },
      {
        id: "gs-8",
        question: "Which AI models does KSEMO use?",
        answer:
          "KSEMO is powered by Google's Gemini family of models. The model used for a reply is chosen automatically for your request, and you can see or change your preferred model from Settings → Preferences.",
      },
      {
        id: "gs-9",
        question: "Is there a limit on how many messages I can send?",
        answer:
          "KSEMO applies fair-use limits per model to keep capacity fair. If you reach a model's daily allowance, KSEMO automatically switches to a fallback model so you can continue — or you can switch models yourself in Settings.",
      },
      {
        id: "gs-10",
        question: "What is the KSEMO Assistant in the corner of the FAQ page?",
        answer:
          "It is a help-center assistant: it answers questions using this help center's content only. It cannot see your conversations or files. Use the main chat screen for conversations with the AI assistant.",
      },
      {
        id: "gs-11",
        question: "Do I need to install anything to use KSEMO?",
        answer:
          "No. KSEMO runs entirely in your browser at its app address. You only need a modern browser and an internet connection. Nothing is installed on your device.",
      },
      {
        id: "gs-12",
        question: "What should I do first after signing in?",
        answer:
          "Open Settings once to review your preferences — choose your preferred model, response style, speech settings, and theme. Then click “New chat” and try a simple question. When you are ready to go further, upload a few files to the Library and explore Voice mode.",
      },
      {
        id: "gs-13",
        question: "Can I try KSEMO before creating an account?",
        answer:
          "When the platform runs without a configured database it provides a built-in demo account so you can explore the full interface immediately. For a personal, persistent workspace you sign in with your Google account.",
      },
      {
        id: "gs-14",
        question: "How do I switch between light and dark themes?",
        answer:
          "Open Settings and choose your theme — Light, Dark, or System. KSEMO also remembers your choice between visits. In Clarity mode, Auto-Play responses are turned off for a calmer reading experience.",
      },
      {
        id: "gs-15",
        question: "Does KSEMO work offline?",
        answer:
          "No. KSEMO needs an internet connection because responses are generated by server-side AI models and your workspace is stored in the cloud. Voice input also relies on the browser's speech services.",
      },
      {
        id: "gs-16",
        question: "Which languages does KSEMO understand?",
        answer:
          "KSEMO understands the major world languages that its underlying Gemini models support — including English, Spanish, French, German, Hindi, Portuguese, Japanese, Korean, Chinese, and Arabic. You can write in one language and ask for an answer in another.",
      },
    ],
  },
  {
    id: "account-security",
    label: "Account & security",
    items: [
      {
        id: "ac-1",
        question: "How do I sign in to KSEMO?",
        answer:
          "Use the “Sign in with Google” button on the access screen. Your Google account securely identifies you and creates your private KSEMO space.",
      },
      {
        id: "ac-2",
        question: "How do I sign out?",
        answer:
          "Click your profile at the bottom of the sidebar and choose Sign out, or open Settings → Security → Sign out. This ends the session in your current browser.",
      },
      {
        id: "ac-3",
        question: "Where do I manage my name and email?",
        answer:
          "Your name and email come from your Google account and are shown read-only in Settings → Account. To change them, update your Google profile and they will reflect in KSEMO.",
      },
      {
        id: "ac-4",
        question: "Can multiple people use the same KSEMO account?",
        answer:
          "KSEMO accounts are personal. Each person should sign in with their own Google account so conversations and files stay private to them.",
      },
      {
        id: "ac-5",
        question: "What happens if I lose access to my Google account?",
        answer:
          "Because signing in depends on Google, recovering your Google account through Google's account recovery is the way back in. Your KSEMO data stays safe and waits for you.",
      },
      {
        id: "ac-6",
        question: "Does KSEMO ever ask for my password?",
        answer:
          "Never. KSEMO only uses Google's official sign-in window. If any page or message asks for your password directly, do not enter it and report it to us immediately.",
      },
      {
        id: "ac-7",
        question: "How do I keep my account secure?",
        answer:
          "Use a strong password and two-step verification on your Google account, avoid sharing your device session, and sign out on shared computers. Review public share links regularly and turn off ones you no longer need.",
      },
      {
        id: "ac-8",
        question: "What security measures protect my KSEMO account and data?",
        answer:
          "KSEMO protects data in several layers:\n- All traffic between your browser and KSEMO is encrypted in transit with HTTPS/TLS.\n- Data at rest is protected by encryption on our cloud infrastructure.\n- Your workspace is private to your account and isolated from other users.\n- Sessions rely on signed, secure cookies scoped to the KSEMO application.\n- Internal access to your content is limited to what is strictly required to operate, debug, or meet legal obligations, under least-privilege controls.\nSee Security measures in the Privacy Policy for the full detail.",
      },
      {
        id: "ac-9",
        question: "Does KSEMO support two-factor authentication?",
        answer:
          "KSEMO itself relies on Google identity; it does not add a separate login of its own. The most effective protection is enabling two-step verification on your Google account — that same protection then guards every KSEMO session you create. Any login problem with Google is handled through Google's own recovery flow.",
      },
      {
        id: "ac-10",
        question: "Is my connection to KSEMO encrypted?",
        answer:
          "Yes. Every connection between your browser and KSEMO uses HTTPS/TLS encryption, and your session is protected by signed, secure cookies. KSEMO also pushes back on broad or informal requests for your data as described in the Privacy Policy.",
      },
      {
        id: "ac-11",
        question:
          "How are my conversations protected from unauthorized access?",
        answer:
          "Conversations are tied to your signed-in identity and are not accessible without an authenticated session. Access is limited to your workspace, data storage is isolated per account, and internal staff access is restricted to what is strictly necessary. Public sharing is always opt-in and per-conversation.",
      },
      {
        id: "ac-12",
        question:
          "What should I do if I suspect my account has been compromised?",
        answer:
          "Act in this order:\n1. Sign out of KSEMO immediately.\n2. Secure your Google account — change your password, review active sessions, and turn on two-step verification.\n3. Review your shared links in KSEMO and disable any you did not create.\n4. Report the suspected compromise from Settings → Feedback for investigation.\nTake the same steps if you see activity in your chats you did not make.",
      },
      {
        id: "ac-13",
        question: "How do I recognize phishing attempts that mention KSEMO?",
        answer:
          "KSEMO never asks for your password, banking details, or one-time codes — neither by email, message, nor in-app. Signs of a phishing attempt:\n- A message pressures you to act or share a login code.\n- The sender address is not the official KSEMO domain.\n- A link leads anywhere except the app address you already use.\nWhen in doubt, do not click the link: open the app from your saved address directly and report the message from Settings → Feedback.",
      },
      {
        id: "ac-14",
        question: "How do I sign out everywhere at once?",
        answer:
          "KSEMO signs out the browser you are currently using. To end sessions on a shared or lost device, sign out of your Google account there or revoke the session from Google's security page — since KSEMO sessions depend on Google identity, ending the Google session ends KSEMO access too.",
      },
      {
        id: "ac-15",
        question: "Does KSEMO store my Google password?",
        answer:
          "No. KSEMO never sees or stores your Google password. It uses Google's official OAuth flow, which hands KSEMO only the identity information you approve — typically your name, email, and account identifier.",
      },
      {
        id: "ac-16",
        question: "Can someone see my account with only an email address?",
        answer:
          "No. A signed-in session is required to view any of your data. An email address alone does not reveal your conversations or files, and public links are disabled until you explicitly turn them on for a specific conversation.",
      },
      {
        id: "ac-17",
        question:
          "What happens to my account if I am inactive for a long time?",
        answer:
          "Your account and data remain in place while you are away. Abandoned or suspended accounts may be purged only after a prolonged inactive period where legally permitted, and we would make reasonable efforts to provide notice first. If you plan to be away, screenshots and exports are the simplest way to keep a copy of what matters.",
      },
    ],
  },
  {
    id: "conversations",
    label: "Conversations & chats",
    items: [
      {
        id: "cn-1",
        question: "Are my conversations saved?",
        answer:
          "Yes. Conversations are stored privately in your account so you can reopen them after refreshing or coming back later. You can rename, archive, share, or permanently delete them anytime.",
      },
      {
        id: "cn-2",
        question: "How do I find an older conversation?",
        answer:
          "Click Search in the sidebar or press Ctrl/Cmd + K. You can search conversation titles and message text, then jump straight to the result.",
      },
      {
        id: "cn-3",
        question: "How do I rename a conversation?",
        answer:
          "Hover over the conversation in the sidebar, click the three-dot menu, and choose Rename. Clear titles make future searches much easier.",
      },
      {
        id: "cn-4",
        question: "What does pinning a conversation do?",
        answer:
          "Pinned conversations stay at the top of your sidebar under “Pinned” so important chats are always one click away. You can unpin them whenever you like.",
      },
      {
        id: "cn-5",
        question: "What happens when I archive a conversation?",
        answer:
          "Archiving tidies your sidebar without deleting anything. Archived conversations move out of Recent, and deleting them permanently is a separate, explicit step.",
      },
      {
        id: "cn-6",
        question: "How do I permanently delete a conversation?",
        answer:
          "Hover over the conversation, open its three-dot menu, choose Delete, and confirm. Permanent deletion removes the conversation and its messages and cannot be undone.",
      },
      {
        id: "cn-7",
        question: "Can I duplicate a conversation?",
        answer:
          "Yes. Choose Duplicate from the conversation menu to create a full copy. It is useful when you want to try a different direction without touching the original.",
      },
      {
        id: "cn-8",
        question: "Can I edit a message I already sent?",
        answer:
          "Yes. Open the menu on your message, choose Edit, and save your changes. KSEMO keeps your earlier version safely recorded and regenerates the response from your edited message.",
      },
      {
        id: "cn-9",
        question: "How do I regenerate a response?",
        answer:
          "Open the menu on any KSEMO response and choose Regenerate. KSEMO writes a fresh reply to the same message without adding a new turn.",
      },
      {
        id: "cn-10",
        question: "How do I stop KSEMO while it is answering?",
        answer:
          "Click the stop button that replaces the send button while a response is streaming, or press Escape. The partial answer is kept so you can continue from there.",
      },
      {
        id: "cn-11",
        question: "Why did a response fail or stop halfway?",
        answer:
          "Short network interruptions can interrupt a response. Your message is kept — simply retry from the failed message or send it again. Completed messages are never lost this way.",
      },
      {
        id: "cn-12",
        question: "How do I use voice input?",
        answer:
          "Click the microphone next to the message box, speak, then confirm when you are done. KSEMO transcribes your speech and sends it as a regular message. Your transcribed text joins the conversation and is edited and deleted like any other message.",
      },
      {
        id: "cn-13",
        question: "Are my voice recordings stored?",
        answer:
          "Your recording is transcribed into text and then treated as a normal conversation message. The raw audio is used only for that transcription and is not kept as part of the conversation.",
      },
      {
        id: "cn-14",
        question: "Can I use a screenshot as context in a message?",
        answer:
          "Yes. Open the plus menu in the message box and choose “Take screenshot”, then grant screen or window permissions when asked. The screenshot attaches to your message like an image for the current conversation.",
      },
      {
        id: "cn-15",
        question: "What happens when I edit or restore a message?",
        answer:
          "Editing a user message keeps the earlier version recorded in that message's version history, and KSEMO regenerates the response from your edited text. You can open a message's history panel to compare versions and restore an older one.",
      },
      {
        id: "cn-16",
        question:
          "How much context can KSEMO consider in a single conversation?",
        answer:
          "The context window depends on the active Gemini model and the size of any attached files. Modern models in KSEMO handle large conversations — roughly comparable to very long documents — but earlier parts of a very long thread or large attachments can move outside the model's active working context. KSEMO includes relevant portions of the visible conversation each turn, and you can always rephrase or open a new chat for a heavy topic.",
      },
      {
        id: "cn-17",
        question: "How do I search within one specific conversation?",
        answer:
          "Use the global search (Ctrl/Cmd + K) and type a distinctive word from that conversation — matching titles and message text will surface it. There is no per-chat search box, but the global search plus the conversation title is the fastest route.",
      },
      {
        id: "cn-18",
        question: "Can I recover a conversation I deleted?",
        answer:
          "Files and conversations that are permanently deleted cannot be recovered. If the item is still in Trash, open Trash and restore it before permanent deletion runs. For items removed long ago, a copy may survive only in your own exports or screenshots — deletion in KSEMO is intentionally direct and permanent.",
      },
      {
        id: "cn-19",
        question: "What is the difference between archiving and deleting?",
        answer:
          "Archiving only hides a conversation from your main list — it keeps everything and can be undone at any time. Deleting is destructive: a conversation moved to Trash remains recoverable for a period, but permanent deletion removes it and its version history forever.",
      },
      {
        id: "cn-20",
        question: "Can I continue a conversation on another device?",
        answer:
          "Yes. Conversations are stored on your server-side account, so signing in on another device shows the same history, files, and preferences. Changes made on one device appear when the other reloads.",
      },
      {
        id: "cn-21",
        question:
          "Why does KSEMO sometimes give a different answer to the same question?",
        answer:
          "AI responses are probabilistic, not deterministic. The same prompt can produce different — but usually equally valid — phrasings on different runs, and Regenerate exists specifically for this. If answers to the same factual question disagree, treat the claims as unverified and check a reliable source.",
      },
      {
        id: "cn-22",
        question: "How do I clear the current conversation and start fresh?",
        answer:
          "Click “New chat” in the sidebar or press Ctrl/Cmd + Shift + O, and optionally rename or archive the previous conversation first. Starting a new chat also resets the conversational context that the AI carries into each answer.",
      },
      {
        id: "cn-23",
        question: "Do very long conversations lose earlier details?",
        answer:
          "As a conversation grows, the model still receives the conversation as context, but answers are shaped more strongly by the most recent turns. If an older detail matters, restate it in your message — and avoid cramming very large documents into one thread when a Library file is the better tool.",
      },
    ],
  },
  {
    id: "library-files",
    label: "Library & files",
    items: [
      {
        id: "lf-1",
        question: "What is the Library?",
        answer:
          "The Library is your private storage for documents and images inside KSEMO. Files you add stay there until you remove them, ready to attach to any conversation.",
      },
      {
        id: "lf-2",
        question: "Which file types can I add?",
        answer:
          "PDFs, Word documents, Excel spreadsheets, PowerPoint presentations, and plain text files (such as TXT, JSON, XML, YAML, and log files). Each file can be up to 25 MB.",
      },
      {
        id: "lf-3",
        question: "How do I add a file to the Library?",
        answer:
          "Click the plus icon in the message box and choose “Add images and files”, or open Library from the sidebar and upload there. The file is saved to your private Library either way.",
      },
      {
        id: "lf-4",
        question: "How do I use a Library file in a conversation?",
        answer:
          "Attach it from the composer's plus menu via “Browse Library”, or open Library and choose “Chat with these files”. KSEMO only sees files you explicitly include in that conversation.",
      },
      {
        id: "lf-5",
        question: "Can KSEMO read images?",
        answer:
          "Yes, when the selected model supports vision. Attach the image to your message and ask about it — screenshots, photos, diagrams, and charts all work.",
      },
      {
        id: "lf-6",
        question: "Can KSEMO read PDFs?",
        answer:
          "Yes. Attach a PDF from your Library and ask questions about its contents. Very large or scanned PDFs may need a smaller section attached instead.",
      },
      {
        id: "lf-7",
        question: "How do I delete a file from my Library?",
        answer:
          "Open Library, hover over the file, and choose Delete, then confirm. Deleting a Library file also removes it from any messages that previously referenced it, and cannot be undone.",
      },
      {
        id: "lf-8",
        question: "Who can see the files in my Library?",
        answer:
          "Only you. Library files are stored privately against your account and are sent to the AI service only at the moment you include them in a conversation.",
      },
      {
        id: "lf-9",
        question: "How can I tell file types apart when browsing my Library?",
        answer:
          "Images show a small thumbnail; every other file type has its own colored icon and label — red for PDF, blue for Word, green for sheets, orange for slides, violet for code and data, and so on.",
      },
      {
        id: "lf-10",
        question: "Are the files I upload encrypted?",
        answer:
          "Yes. Library files live in private object storage that is encrypted at rest, and they are reached only through short-lived, authorized links for your session. They are transferred over HTTPS and are accessible only with an authenticated session.",
      },
      {
        id: "lf-11",
        question: "Is there a limit on how many files I can store?",
        answer:
          "Each file is limited to 25 MB and to supported types. There is no arbitrary cap on the number of files in a Library during the launch period; fair-use and storage considerations may apply as the service evolves.",
      },
      {
        id: "lf-12",
        question: "Can I rename a file in the Library?",
        answer:
          "Files can be renamed through the Library menu. Staying organized with clear names makes them much easier to find and attach later.",
      },
      {
        id: "lf-13",
        question: "Can KSEMO analyze very long documents or books?",
        answer:
          "KSEMO extracts and reads the text of supported files automatically. For extremely long documents, attach the section you actually need — a chapter rather than an entire book — because very large bodies of text can exceed what the model can fully weigh in one answer.",
      },
      {
        id: "lf-14",
        question: "What happens to my files if my account or plan changes?",
        answer:
          "Your files belong to your account. Deleting your account removes them; nothing in the Terms of Service converts your uploads into KSEMO's property. If paid plans are introduced later, storage capacity would be disclosed in advance and existing files would not simply disappear.",
      },
      {
        id: "lf-15",
        question: "Can files be shared through a conversation's public link?",
        answer:
          "A public link shares the conversation's messages, which may include text drawn from your files. The file itself is not downloadable through the link, and the shared view never exposes your Library or other conversations.",
      },
      {
        id: "lf-16",
        question: "How does KSEMO extract text from scanned PDFs or images?",
        answer:
          "KSEMO uses modern AI vision and text-extraction to read screenshots, photos, diagrams, and digitized-paper documents. Clean images and supported file types give the best results; handwriting and heavy scan noise can reduce accuracy.",
      },
    ],
  },
  {
    id: "sharing-export",
    label: "Sharing & export",
    items: [
      {
        id: "sh-1",
        question: "Can I share a conversation with someone?",
        answer:
          "Yes. Open the conversation's menu, choose Share, and enable public link sharing. Anyone with the link can read that conversation until you turn sharing off.",
      },
      {
        id: "sh-2",
        question: "Who can see a shared conversation?",
        answer:
          "Anyone who has the link. Shared links are view-only, do not expose your other conversations, and can be switched off at any time from the same Share dialog.",
      },
      {
        id: "sh-3",
        question: "How do I stop sharing a conversation?",
        answer:
          "Open the Share dialog for that conversation and disable public sharing. The old link stops working immediately.",
      },
      {
        id: "sh-4",
        question: "Can I export a conversation as a document?",
        answer:
          "Yes. From the conversation menu choose Export and pick PDF or Word. The file downloads straight from your browser.",
      },
      {
        id: "sh-5",
        question: "Can I share a single message instead of a whole chat?",
        answer:
          "Yes. Every message has a share action that copies it to your clipboard, or opens your device's native share sheet on mobile.",
      },
      {
        id: "sh-6",
        question: "Do shared links update when the conversation continues?",
        answer:
          "A shared link shows the conversation as it is when viewed. New messages become visible on the link until you turn sharing off, so double-check before continuing a sensitive topic.",
      },
      {
        id: "sh-7",
        question:
          "Is it safe to share conversations containing personal details?",
        answer:
          "Treat a public link like a printed page: anyone holding it can read it. Remove sensitive details, or keep sharing disabled, when a conversation contains private information.",
      },
      {
        id: "sh-8",
        question: "Do people need a KSEMO account to view a shared link?",
        answer:
          "No. Anyone with the link can read the shared conversation without signing in. The shared view is read-only and shows only that conversation — never your other chats or Library files.",
      },
      {
        id: "sh-9",
        question: "Can I password-protect a shared conversation link?",
        answer:
          "Not currently. Public links are protected by their obscurity — only people you give the link to can open it — rather than a password. If the content is sensitive enough to need a password, consider sending an export directly instead of publishing a link.",
      },
      {
        id: "sh-10",
        question: "Do shared links ever expire?",
        answer:
          "Links stay valid until you turn sharing off or delete the conversation — they do not expire on their own. Turn sharing off in the Share dialog to invalidate a link immediately.",
      },
      {
        id: "sh-11",
        question: "Can I download a shared conversation as a file?",
        answer:
          "As the owner you can export any of your conversations to PDF or Word from the conversation menu. Recipients of a public link see a read-only view; they cannot export or edit it.",
      },
      {
        id: "sh-12",
        question: "What exactly is included in an export?",
        answer:
          "An export captures the conversation's messages in the order they appear, including edited and regenerated content as shown on screen. Exports are generated from what is stored, so a conversation truncated inside KSEMO will export in its stored form — export before removing parts you want to keep.",
      },
      {
        id: "sh-13",
        question: "Can I edit a conversation that someone shared with me?",
        answer:
          "No. Shared links are strictly read-only. As the owner you edit the original; anyone else can only view the shared copy. Shared views reveal no controls for messaging or editing.",
      },
      {
        id: "sh-14",
        question: "How do I copy the link to a conversation?",
        answer:
          "Open the Share dialog for the conversation and copy the public link it displays. The link is created the moment public sharing is enabled, and it can be regenerated or disabled from the same dialog.",
      },
    ],
  },
  {
    id: "privacy-data",
    label: "Privacy & data control",
    items: [
      {
        id: "pd-1",
        question: "What data does KSEMO store about me?",
        answer:
          "Your account profile from Google, your conversations and messages, files you add to your Library, and your preferences. Nothing else is collected beyond what the service needs to run.",
      },
      {
        id: "pd-2",
        question: "Is my data used to train AI models?",
        answer:
          "Your content is processed to generate responses for you. It is not sold, and it is not shared with advertising networks. See the Privacy Policy for the full detail.",
      },
      {
        id: "pd-3",
        question: "How do I delete everything?",
        answer:
          "Delete individual conversations and Library files from their respective menus. Permanently deleted items cannot be recovered.",
      },
      {
        id: "pd-4",
        question: "Where are my files kept?",
        answer:
          "Library files live in private storage tied to your account, not inside the chat database. Access is limited to features you explicitly use, such as attaching a file to a message.",
      },
      {
        id: "pd-5",
        question: "Can anyone at KSEMO read my conversations?",
        answer:
          "Conversations are private to your account. They are accessed only where strictly necessary to operate, debug, or comply with legal obligations, under strict internal controls.",
      },
      {
        id: "pd-6",
        question: "What preferences does KSEMO remember?",
        answer:
          "Your chosen model, response style, custom instructions, speech rate, autoplay setting, and reduce-motion preference. All of them live in Settings and update instantly when saved.",
      },
      {
        id: "pd-7",
        question: "How do I turn off automatic read-aloud of replies?",
        answer:
          "Open Settings → Preferences and switch off “Auto-play responses”. You can always play a specific reply manually from its message menu.",
      },
      {
        id: "pd-8",
        question: "Does KSEMO comply with privacy laws like GDPR?",
        answer:
          "KSEMO is built on privacy-by-design principles: minimal collection, explicit controls, and easy deletion. The Privacy Policy explains how these principles apply to your data in practice.",
      },
      {
        id: "pd-9",
        question: "How do I delete my entire account?",
        answer:
          "Open Settings → Account and choose “Delete account”, then confirm. This permanently removes your account and the data tied to it — conversations, files, and memories — and signs you out. This cannot be undone.",
      },
      {
        id: "pd-10",
        question: "Does KSEMO use cookies or trackers?",
        answer:
          "KSEMO uses a strictly necessary session cookie to keep you signed in and local storage for interface preferences. There are no advertising cookies, no third-party tracking scripts, and no fingerprinting. KSEMO does not build advertising profiles and does not track you across other sites.",
      },
      {
        id: "pd-11",
        question: "How do I request a copy of all my data?",
        answer:
          "Most of your data is already exportable from the product: conversations export to PDF or Word, and your other content is visible within the app itself. For a broader access request beyond what the app exposes, contact us from Settings → Feedback with the email on your account, and we will provide the data you are entitled to within the window required by applicable law.",
      },
      {
        id: "pd-12",
        question: "How long is my data stored after I delete it?",
        answer:
          "Permanent deletion removes content from the active system promptly; residual encrypted backups expire on the backup rotation schedule and are then gone entirely. Items in Trash remain recoverable until they are permanently deleted. KSEMO keeps only the minimum operational records required for security and compliance, for as long as necessary.",
      },
      {
        id: "pd-13",
        question: "Can I use KSEMO without creating an account?",
        answer:
          "The main chat experience works while you sign in — there is no guest mode that stores private conversations without an account. When the platform runs without a configured database it offers a demo account purely as a preview of the interface.",
      },
      {
        id: "pd-14",
        question: "Does KSEMO comply with CCPA, GDPR, and similar laws?",
        answer:
          "KSEMO is engineered around privacy-by-design: minimal collection, explicit user controls, and direct deletion. The Privacy Policy maps these protections to GDPR, CCPA/CPRA, UK GDPR, Colorado/Connecticut/Utah/Virginia consumer statutes, PIPEDA, and LGPD, and KSEMO honors the strongest protections that apply to you — including the right to access, correct, export, and delete your information.",
      },
      {
        id: "pd-15",
        question: "How does KSEMO respond to data breaches?",
        answer:
          "The service is monitored for suspicious activity and unauthorized access. If we confirm a breach that materially compromises your personal information, we notify affected users without undue delay, describing what happened and what we are doing, and we notify regulators where the law requires it. See Data breach response in the Privacy Policy.",
      },
      {
        id: "pd-16",
        question: "Does KSEMO monitor or moderate my conversations?",
        answer:
          "Your conversations are private to your account; KSEMO does not routinely review chat content. Automated safeguards may flag clear abuse — such as spam, malware, or content that endangers minors — and content is accessed manually only where strictly necessary to operate, debug, or respond to lawful requests under policy and legal controls.",
      },
      {
        id: "pd-17",
        question: "How do I manage sensitive information about myself?",
        answer:
          "You control the store: keep Memory off if you do not want durable facts saved, do not attach files you would rather not process, and turn sharing off when a conversation touches private matters. Export what you need and delete what you do not. The product favors forgetfulness unless you choose otherwise.",
      },
    ],
  },
  {
    id: "memory-personalization",
    label: "Memory & personalization",
    items: [
      {
        id: "mm-1",
        question: "What is KSEMO Memory?",
        answer:
          "Memory lets KSEMO automatically analyze your conversations and remember the facts, preferences, and context that matter, so future replies are consistent and personal. You control it with a single toggle in Settings → Memory.",
      },
      {
        id: "mm-2",
        question: "Is Memory on by default?",
        answer:
          "No. Memory starts off for every account. Nothing is analyzed or remembered until you switch Memory on in Settings → Memory.",
      },
      {
        id: "mm-3",
        question: "How do I turn Memory on or off?",
        answer:
          "Open Settings → Memory and toggle the single Memory switch. On means conversations are analyzed automatically; off means they are not.",
      },
      {
        id: "mm-4",
        question: "What does KSEMO save as a memory?",
        answer:
          "Durable facts you share in conversation — things like “I work as a teacher”, “I prefer email over calls”, “I'm planning a trip to Portugal in spring”, and similar durable details. Transient small talk is not remembered.",
      },
      {
        id: "mm-5",
        question: "Are sensitive or personal details saved when Memory is on?",
        answer:
          "Yes. KSEMO captures the durable facts you actually tell it, which can include personal details such as your job, family, location, or health, once Memory is enabled. Do not share information you would not want saved, or keep Memory off.",
      },
      {
        id: "mm-6",
        question: "What happens when I turn Memory off?",
        answer:
          "KSEMO stops analyzing new conversations and stops using your saved memories in replies. The memories already stored stay in your account while Memory is off, and are used again only if you turn Memory back on. To remove everything, delete your account or contact us from Settings → Feedback.",
      },
      {
        id: "mm-7",
        question: "Where can I see how many memories are saved?",
        answer:
          "Settings → Memory shows the current memory status and how many memories are saved. KSEMO does not currently offer a separate per-fact memory manager, so to review or clear specific facts, contact us from Settings → Feedback.",
      },
      {
        id: "mm-8",
        question:
          "Does KSEMO use my memories to train AI models or share them?",
        answer:
          "No. Memories stay private in your account. They are used only to personalize the replies KSEMO generates for you, under the same rules as the rest of your content.",
      },
      {
        id: "mm-9",
        question: "Can I see or edit individual saved memories?",
        answer:
          "Settings → Memory shows the memory status and count. A per-fact memory manager is not available yet, but you can prevent new captures by turning Memory off and can request a full memory review or clearing from Settings → Feedback.",
      },
      {
        id: "mm-10",
        question: "Do my memories sync across devices?",
        answer:
          "Yes. Memories are stored with your account, so the same preferences and facts are used regardless of which device you sign in from. This is what keeps replies consistent wherever you chat.",
      },
      {
        id: "mm-11",
        question: "Can a saved memory be wrong? How do I correct it?",
        answer:
          "A captured fact reflects what was stated in conversation at the time, so it can become outdated — for example changing jobs. Correct it by stating the new fact in a fresh message (“I now work as X”), which KSEMO captures as the updated fact. For a full review or removal of specific stored facts, contact us from Settings → Feedback.",
      },
      {
        id: "mm-12",
        question: "Are memories included when I export a conversation?",
        answer:
          "An export contains the conversation as shown, including any place where a memory-shaped fact appears in text. The memory store itself is account-level and is not attached to a single conversation's export.",
      },
      {
        id: "mm-13",
        question: "How is Memory stored and protected?",
        answer:
          "Memories are stored privately with your account under the same security controls as the rest of your content — encrypted transport, encryption at rest, and restricted internal access. They are not sold, not shared with advertising networks, and not used to train third-party models.",
      },
    ],
  },
  {
    id: "ai-behavior",
    label: "AI & models",
    items: [
      {
        id: "ai-1",
        question: "Which AI models power KSEMO, and why does the model matter?",
        answer:
          "KSEMO is powered by Google's Gemini family of models, accessed through a server-side API. Different models balance speed, intelligence, and cost differently: some are tuned for fast everyday chat, others for complex reasoning, documents, or code. You can see and change your preferred model from Settings → Preferences.",
      },
      {
        id: "ai-2",
        question: "How does KSEMO decide which model answers my message?",
        answer:
          "Your selected preference guides the default, and KSEMO automatically chooses an appropriate model for the request. When a model's daily fair-use allowance is spent, KSEMO falls back to an available model so you can keep working — the reply still appears in your conversation normally.",
      },
      {
        id: "ai-3",
        question:
          "Why do I sometimes get different answers to the same question?",
        answer:
          "AI responses are generated probabilistically. The same prompt can produce different phrasings — sometimes different facts — on different runs. If a factual question is important, compare responses (Regenerate lets you try again) and verify against a reliable source before relying on the answer.",
      },
      {
        id: "ai-4",
        question: "Can KSEMO access the internet for live information?",
        answer:
          "KSEMO responds from its model's training knowledge and the content you provide — attachments, memories, and the conversation. It does not browse the live web on its own. For actionable things that change quickly — prices, flight times, breaking news — check a live source directly.",
      },
      {
        id: "ai-5",
        question:
          "How much of my conversation does KSEMO remember while answering?",
        answer:
          "Each turn, KSEMO receives the visible conversation as working context plus anything you attach, so it can refer back to earlier messages in the same chat. Everything outside that active conversation — other chats, and your account's facts — is only consulted when you turn on Memory, which pulls relevant saved facts into context automatically.",
      },
      {
        id: "ai-6",
        question:
          "What is a hallucination, and how do I avoid relying on wrong AI answers?",
        answer:
          "Hallucinations are confident answers that models can produce for things that are not true — usually about obscure facts, recent events, or invented references. To reduce risk:\n- Ask for steps or a verifiable breakdown instead of a single vague claim.\n- Ask the model to distinguish what comes from your attached files versus general knowledge.\n- Check invented-looking citations and numbers before publishing.\n- Use your Library files when answers must be grounded in your own documents.",
      },
      {
        id: "ai-7",
        question:
          "Can I make KSEMO answer more creatively, precisely, or concisely?",
        answer:
          "Yes, two ways:\n- Response style in Settings → Preferences (Balanced, Concise, Creative, Analytical) shifts the default tone.\n- Custom instructions add standing rules (“Always format answers as bullet points”, “Write for a Grade 9 reader”).\nYou can also steer a single reply, for example: “Answer in five sentences with one example.”",
      },
      {
        id: "ai-8",
        question: "Can KSEMO read images, documents, and data together?",
        answer:
          "Yes. Attach images and documents into one message, or attach them with a question, and KSEMO can combine the evidence — for example “Summarize this PDF and compare it with this screenshot”. The best results come from smaller, well-labeled attachments.",
      },
      {
        id: "ai-9",
        question: "What happens when I run out of a model's daily allowance?",
        answer:
          "KSEMO automatically switches to a fallback model so you can continue chatting without interruption. You can also switch your preferred model in Settings to a fresh daily allowance. Limits exist to keep capacity fair for everyone and are explained in Plans & usage limits.",
      },
      {
        id: "ai-10",
        question:
          "Does KSEMO learn from my conversations over time without Memory?",
        answer:
          "No. Within a single conversation the chat itself is the context, but nothing is carried across conversations unless you turn on Memory. With Memory off, each new chat starts without knowledge of your earlier chats and facts.",
      },
      {
        id: "ai-11",
        question: "Can KSEMO generate code, formulas, or structured data?",
        answer:
          "Yes. KSEMO can write code, Excel formulas, SQL queries, JSON structures, and step-by-step procedures, and it can create documents (PDF, Word, Excel, PowerPoint, Text) directly through the document menu in the composer. Treat generated code as a draft to review and test before production use.",
      },
      {
        id: "ai-12",
        question: "How accurate are KSEMO's answers about recent events?",
        answer:
          "The underlying models were trained on data up to a cutoff and do not browse the web, so very recent events may be unknown or described inaccurately. For anything time-sensitive, use current, verifiable sources alongside KSEMO. The most reliable things to ask about are your own documents and files, which KSEMO reads directly.",
      },
    ],
  },
  {
    id: "voice-accessibility",
    label: "Voice & accessibility",
    items: [
      {
        id: "va-1",
        question: "Which browsers and devices support voice input?",
        answer:
          "Voice input uses your browser's speech services and works in current versions of Chrome, Edge, and Safari on desktop and mobile, where a microphone is available. Firefox users can typically write text normally, though browser speech support varies by operating system.",
      },
      {
        id: "va-2",
        question: "What languages are supported for voice input and output?",
        answer:
          "Voice follows what your browser's speech engine provides — typically the major languages on your device (English, Spanish, French, German, and more on modern operating systems). Set the desired language in your system's speech settings, and KSEMO will follow it. Spoken replies use the speech rate you set in Settings.",
      },
      {
        id: "va-3",
        question: "Can I choose a different voice for responses?",
        answer:
          "KSEMO reads replies aloud using the text-to-speech voices available in your browser and operating system. You can control the speed (speech rate) in Settings and, depending on your browser, its voice picker can choose which voice is used.",
      },
      {
        id: "va-4",
        question:
          "What is Voice mode and how is it different from the microphone button?",
        answer:
          "Voice mode is a full hands-free conversation: KSEMO listens, answers out loud, and keeps listening so you can keep talking — with live subtitles on screen. The single microphone button is lighter: it records one turn, transcribes it into your message box, and you then send it as a normal message.",
      },
      {
        id: "va-5",
        question: "What are live subtitles in Voice mode?",
        answer:
          "While KSEMO speaks in Voice mode, subtitles show the response as text on screen so you can follow along or read in noisy environments. The subtitles are display-only during playback; the underlying reply is saved in the conversation as a normal message.",
      },
      {
        id: "va-6",
        question: "Can I interrupt KSEMO while it is speaking?",
        answer:
          "Yes. In Voice mode you can speak over or tap the response to interrupt; in normal mode, the stop button or the Escape key halts a streaming reply. Interrupting keeps the text produced so far so you can continue from there.",
      },
      {
        id: "va-7",
        question: "Does KSEMO support keyboard-only navigation and shortcuts?",
        answer:
          "Yes. KSEMO is built to work without a mouse: Tab moves through controls, Enter sends messages, Escape stops generation or closes dialogs, Ctrl/Cmd + K opens search, and Ctrl/Cmd + Shift + O starts a new chat. All interactive elements expose accessible labels and focus states.",
      },
      {
        id: "va-8",
        question:
          "Does KSEMO work with screen readers and the reduce-motion setting?",
        answer:
          "KSEMO follows accessibility best practice: semantic markup, labeled controls, and high-contrast focus styles work with popular screen readers. If you prefer less animation, turn on the reduce-motion preference in Settings and KSEMO will tone down decorative motion. The Accessibility section of the Terms describes our commitment to inclusive design.",
      },
    ],
  },
  {
    id: "plans-limits",
    label: "Plans & usage limits",
    items: [
      {
        id: "pl-1",
        question: "What are the fair-use limits and how do they work?",
        answer:
          "Fair-use limits are per-model daily allowances designed to keep capacity fair for everyone. Each day the limit resets on a rolling cycle, and switching models gives you a separate allowance. Their purpose is protecting service quality, not restricting normal personal use.",
      },
      {
        id: "pl-2",
        question: "What happens when I reach a usage limit?",
        answer:
          "KSEMO automatically falls back to another available model so your work is not interrupted. You can also switch your preferred model in Settings to continue on a fresh daily allowance. If limits are ever removed or relaxed, this page will be updated.",
      },
      {
        id: "pl-3",
        question:
          "What counts toward a usage limit — messages, characters, or files?",
        answer:
          "Request activity counts toward the active model's allowance. Heavy usage — such as very long documents, many rapid messages, or repeated large attachments — reaches the limit faster because each request uses more capacity.",
      },
      {
        id: "pl-4",
        question: "Will KSEMO remain free, or will there be paid plans?",
        answer:
          "KSEMO is currently free during its launch period. If paid plans are introduced later, the Terms commit us to clearly disclosing price, billing cycle, and inclusions before you subscribe; recurring plans would be cancelable before renewal, taxes shown at checkout, and refunds handled per the plan terms.",
      },
      {
        id: "pl-5",
        question: "Are limits the same for every user and region?",
        answer:
          "During the launch period limits are applied uniformly rather than by region or status. If this changes, the updated rules will be reflected on this page and in the Terms before they take effect.",
      },
      {
        id: "pl-6",
        question: "I believe I was charged or limited wrongly. What do I do?",
        answer:
          "Contact us from Settings → Feedback before initiating any payment dispute. Describe exactly what you expected versus what happened, and we will investigate and resolve it. Free usage never creates an entitlement to a specific level of availability.",
      },
    ],
  },
  {
    id: "troubleshooting",
    label: "Troubleshooting",
    items: [
      {
        id: "tr-1",
        question: "KSEMO is not responding. What should I do?",
        answer:
          "Check your internet connection first, then stop the current response and resend your message. If the problem continues, reload the page — completed conversations are safe on the server.",
      },
      {
        id: "tr-2",
        question: "The page looks frozen after switching chats quickly.",
        answer:
          "Stop the running response with the stop button or Escape, then select the chat again. KSEMO prevents mid-response switching to protect your history, and this clears it.",
      },
      {
        id: "tr-3",
        question: "A file upload failed. What are the limits?",
        answer:
          "Files must be a supported type and under 25 MB each. If you are within the limits, check your connection and try again — very large documents may need splitting into smaller parts.",
      },
      {
        id: "tr-4",
        question: "Search is not finding something I know exists.",
        answer:
          "Search matches titles and message text but needs at least two characters. Try a distinctive word from the message rather than a short or common term.",
      },
      {
        id: "tr-5",
        question: "Keyboard shortcuts are not working.",
        answer:
          "Make sure no dialog is capturing the keyboard and that your focus is inside the KSEMO page. Shortcuts use Ctrl/Cmd + K for search and Ctrl/Cmd + Shift + O for a new chat.",
      },
      {
        id: "tr-6",
        question: "How do I report a bug or suggest a feature?",
        answer:
          "Open Settings → Feedback and use the feedback button to email us. Describe what you expected and what happened — screenshots help a lot.",
      },
      {
        id: "tr-7",
        question:
          "My microphone is not working for voice input. What should I do?",
        answer:
          "Check the browser permission bar — allow microphone access for the KSEMO site and try again. Then confirm the correct microphone is selected in your browser's site settings. If you are on a laptop, check that no privacy switch is muting the internal mic, and close other tabs that may hold the microphone.",
      },
      {
        id: "tr-8",
        question: "The screenshot capture is not working. What should I do?",
        answer:
          "Screenshot capture requires a screen or window permission. Grant it in the browser prompt that appears when you choose “Take screenshot”. If nothing happens, reload the page and try again, or use your operating system's own screenshot tool and attach the image as a regular file.",
      },
      {
        id: "tr-9",
        question: "My download or export is blocked. What should I do?",
        answer:
          "Check your browser's download settings — pop-up blockers or strict download policies can silently block exports. Allow downloads for the KSEMO site, then retry the export. The document is generated fresh each time, so a reloaded export is never stale.",
      },
      {
        id: "tr-10",
        question: "KSEMO says my file could not be read. What should I do?",
        answer:
          "Confirm the file is a supported type and under 25 MB, and that it was uploaded successfully in the Library. Password-protected PDFs or files with unusual internal structures may resist extraction — try a plain version or split the content into smaller sections.",
      },
      {
        id: "tr-11",
        question: "Voice responses are not playing audio. What should I do?",
        answer:
          "Check that your system's audio output is on and that the tab is not muted. If responses previously played aloud, open Settings → Preferences and confirm Auto-play is enabled — otherwise play a specific reply from its message menu.",
      },
      {
        id: "tr-12",
        question:
          "The page says I am offline or cannot reach the server. What should I do?",
        answer:
          "Confirm your connection by opening another site. If you are online, wait a moment and reload — KSEMO sometimes performs short maintenance windows. Completed conversations survive on the server and will reappear after a successful reload.",
      },
      {
        id: "tr-13",
        question: "I see an error I do not recognize. Where can I get help?",
        answer:
          "Write down the exact message and what you were doing, then reach us from Settings → Feedback. Include the approximate time and your browser and operating system versions if you can — that combination lets us reproduce and fix most issues quickly.",
      },
    ],
  },
];

export const FAQ_ITEM_COUNT = FAQ_CATEGORIES.reduce(
  (total, category) => total + category.items.length,
  0
);

export function searchFaq(query: string): Array<{
  category: FaqCategory;
  items: FaqItem[];
  matchedCategory?: boolean;
}> {
  const normalized = query.trim().toLowerCase();
  if (!normalized)
    return FAQ_CATEGORIES.map(category => ({
      category,
      items: category.items,
    }));
  const tokens = normalized
    .split(/\s+/)
    .filter(token => token.length > 2 && !STOP_WORDS.has(token));
  const meaningfulTokens = tokens.length ? tokens : [normalized];
  // A question matching every searched word outranks one matching only some.
  const requiredMatches =
    meaningfulTokens.length <= 2 ? 1 : Math.ceil(meaningfulTokens.length / 2);
  const matchesAll = (haystack: string) =>
    haystack.includes(normalized) ||
    meaningfulTokens.every(token => haystack.includes(token));
  return FAQ_CATEGORIES.map(category => {
    const matchedCategory = matchesAll(category.label.toLowerCase());
    const items = matchedCategory
      ? category.items
      : category.items
          .map(item => {
            const haystack = `${item.question} ${item.answer}`.toLowerCase();
            const score = meaningfulTokens.filter(token =>
              haystack.includes(token)
            ).length;
            return { item, score };
          })
          .filter(entry => entry.score >= requiredMatches)
          .sort((a, b) => b.score - a.score)
          .map(entry => entry.item);
    return { category, items, matchedCategory };
  }).filter(section => section.items.length > 0);
}

const STOP_WORDS = new Set([
  "the",
  "and",
  "for",
  "you",
  "your",
  "with",
  "that",
  "this",
  "have",
  "are",
  "can",
  "how",
  "what",
  "when",
  "where",
  "why",
  "does",
  "did",
  "will",
  "would",
  "should",
  "could",
  "into",
  "from",
  "about",
  "there",
  "their",
  "them",
  "then",
  "than",
  "they",
  "been",
  "being",
  "were",
  "was",
  "has",
  "had",
  "not",
  "but",
  "all",
  "any",
  "out",
  "get",
  "got",
  "use",
  "using",
  "used",
  "ksemo",
]);

function tokenize(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(token => token.length > 2 && !STOP_WORDS.has(token));
}

export type AssistantReply = { answer: string; related: FaqItem[] };

export function answerFromFaq(query: string): AssistantReply {
  const tokens = tokenize(query);
  if (!tokens.length) {
    return {
      answer:
        "Could you rephrase that? For example, ask about files, sharing, your account, or how the AI answers work.",
      related: [],
    };
  }
  const scored = FAQ_CATEGORIES.flatMap(category =>
    category.items.map(item => {
      const questionTokens = new Set(tokenize(item.question));
      const answerText = item.answer.toLowerCase();
      let score = 0;
      for (const token of tokens) {
        if (questionTokens.has(token)) score += 4;
        else if (item.question.toLowerCase().includes(token)) score += 2;
        if (answerText.includes(token)) score += 1;
      }
      return { item, score };
    })
  )
    .filter(entry => entry.score > 0)
    .sort((a, b) => b.score - a.score);
  if (!scored.length || scored[0].score < 2) {
    return {
      answer:
        "I could not find a confident answer in the help center. Try rephrasing, browse the categories above, or contact us from Settings → Feedback.",
      related: [],
    };
  }
  const best = scored.slice(0, 3);
  const primary = best[0].item;
  const extras = best.slice(1).map(entry => entry.item);
  const combined = [
    primary.answer,
    ...extras.slice(0, 1).map(item => item.answer),
  ];
  return {
    answer: combined.join("\n\n"),
    related: extras.length > 1 ? extras.slice(1) : [],
  };
}

export const ASSISTANT_SUGGESTIONS = [
  "How does Memory work?",
  "Which AI models power KSEMO?",
  "How do I keep my account secure?",
  "Which file types can I add?",
  "How do I share a conversation?",
  "How do I delete my data?",
];
