import { execFile, execSync } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";
import crypto from "crypto";

let cachedPythonPath: string | null = null;

/**
 * Locate the available Python executable on the system.
 */
export async function getPythonExecutable(): Promise<string> {
  if (cachedPythonPath) {
    return cachedPythonPath;
  }

  const envPath = process.env.PYTHON_PATH;
  if (envPath && fs.existsSync(envPath)) {
    cachedPythonPath = envPath;
    return cachedPythonPath;
  }

  const candidates = process.platform === "win32"
    ? [
        "py",
        "python",
        "python3",
        "C:\\Users\\sskri\\AppData\Local\\Programs\\Python\\Python310\\python.exe",
        "C:\\Python310\\python.exe",
        "C:\\Python311\\python.exe",
        "C:\\Python312\\python.exe"
      ]
    : ["python3", "python"];

  for (const cmd of candidates) {
    try {
      const output = execSync(`${cmd} --version`, {
        encoding: "utf-8",
        stdio: ["ignore", "pipe", "ignore"],
        timeout: 2000,
      });
      if (output && output.toLowerCase().includes("python")) {
        cachedPythonPath = cmd;
        return cachedPythonPath;
      }
    } catch {
      // Continue to next candidate
    }
  }

  throw new Error("Python 3 executable not found in system PATH or common locations.");
}

export interface PythonExecutionResult {
  success: boolean;
  fileBuffer: Buffer;
  stdout: string;
  stderr: string;
  error?: string;
}

/**
 * Execute Python code in an isolated temporary directory.
 * The script is expected to output a file at `outputFilePath`.
 */
export async function executePythonCode(
  scriptContent: string,
  outputFileName: string = "output.bin",
  timeoutMs: number = 30000
): Promise<PythonExecutionResult> {
  const pythonPath = await getPythonExecutable();

  const tempDir = path.join(os.tmpdir(), "ksemo-py-" + crypto.randomUUID());
  await fs.promises.mkdir(tempDir, { recursive: true });

  const scriptPath = path.join(tempDir, "generate_file.py");
  const outputPath = path.join(tempDir, outputFileName);

  // Replace placeholder or ensure output path is passed as command line argument or injected
  // Scripts generated by pythonGenerator will expect the output filename as the first argument sys.argv[1]
  await fs.promises.writeFile(scriptPath, scriptContent, "utf-8");

  return new Promise<PythonExecutionResult>((resolve) => {
    execFile(
      pythonPath,
      [scriptPath, outputPath],
      {
        cwd: tempDir,
        timeout: timeoutMs,
        maxBuffer: 10 * 1024 * 1024, // 10MB
        env: { ...process.env, PYTHONIOENCODING: "utf-8" },
      },
      async (error, stdout, stderr) => {
        let fileBuffer = Buffer.alloc(0);
        let success = false;
        let errorMessage: string | undefined = undefined;

        try {
          if (error) {
            errorMessage = error.message;
            if (stderr) {
              errorMessage += `\nStderr: ${stderr}`;
            }
          } else if (fs.existsSync(outputPath)) {
            fileBuffer = await fs.promises.readFile(outputPath);
            success = true;
          } else {
            errorMessage = `Expected output file ${outputFileName} was not generated.\nStdout: ${stdout}\nStderr: ${stderr}`;
          }
        } catch (e: any) {
          errorMessage = e.message || String(e);
        } finally {
          // Cleanup temp files
          try {
            await fs.promises.rm(tempDir, { recursive: true, force: true });
          } catch {
            // Ignore cleanup errors
          }

          resolve({
            success,
            fileBuffer,
            stdout: stdout || "",
            stderr: stderr || "",
            error: errorMessage,
          });
        }
      }
    );
  });
}
