-- OAuth credentials for optional Google Drive and OneDrive imports.
-- Token columns contain AES-256-GCM ciphertext generated by the application.
CREATE TABLE IF NOT EXISTS user_integrations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('google', 'microsoft')),
  token_ciphertext TEXT NOT NULL,
  token_iv TEXT NOT NULL,
  token_tag TEXT NOT NULL,
  refresh_ciphertext TEXT,
  refresh_iv TEXT,
  refresh_tag TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  account_email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, provider)
);
CREATE INDEX IF NOT EXISTS idx_user_integrations_user_id ON user_integrations(user_id);
ALTER TABLE user_integrations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manages cloud integrations" ON user_integrations;
CREATE POLICY "Service role manages cloud integrations" ON user_integrations
  FOR ALL TO service_role USING (true) WITH CHECK (true);
